#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers
ynh_script_progression "Actualisation du catalogue ARCenal..."
arcenal_catalog_add
arcenal_repair_legacy_portal_version
arcenal_repair_legacy_portal_backup
